"""
Fully irregular verbs: hardcoded paradigms for tenses/moods that no rule
predicts. Anything not listed for a given verb/tense falls back to the
regular/stem-change/ortho engine layered on the verb's irregular stems
(handled in paradigm.py) -- e.g. future/conditional only need an irregular
stem (tendr-, dir-, har-...), not a full override.

Structure: IRREGULAR[verb][tense] = {person: form}
Persons follow conj_engine.stems.PERSONS order: yo, tu, el, nosotros, vosotros, ellos
"""

IRREGULAR = {
    "ser": {
        "present_indicative": {"yo": "soy", "tu": "eres", "el": "es", "nosotros": "somos", "vosotros": "sois", "ellos": "son"},
        "preterite": {"yo": "fui", "tu": "fuiste", "el": "fue", "nosotros": "fuimos", "vosotros": "fuisteis", "ellos": "fueron"},
        "imperfect_indicative": {"yo": "era", "tu": "eras", "el": "era", "nosotros": "éramos", "vosotros": "erais", "ellos": "eran"},
        "present_subjunctive": {"yo": "sea", "tu": "seas", "el": "sea", "nosotros": "seamos", "vosotros": "seáis", "ellos": "sean"},
        "imperfect_subjunctive_ra": {"yo": "fuera", "tu": "fueras", "el": "fuera", "nosotros": "fuéramos", "vosotros": "fuerais", "ellos": "fueran"},
        "imperfect_subjunctive_se": {"yo": "fuese", "tu": "fueses", "el": "fuese", "nosotros": "fuésemos", "vosotros": "fueseis", "ellos": "fuesen"},
        "gerund": "siendo",
        "past_participle": "sido",
    },
    "estar": {
        "present_indicative": {"yo": "estoy", "tu": "estás", "el": "está", "nosotros": "estamos", "vosotros": "estáis", "ellos": "están"},
        "preterite": {"yo": "estuve", "tu": "estuviste", "el": "estuvo", "nosotros": "estuvimos", "vosotros": "estuvisteis", "ellos": "estuvieron"},
        "present_subjunctive": {"yo": "esté", "tu": "estés", "el": "esté", "nosotros": "estemos", "vosotros": "estéis", "ellos": "estén"},
        "imperfect_subjunctive_ra": {"yo": "estuviera", "tu": "estuvieras", "el": "estuviera", "nosotros": "estuviéramos", "vosotros": "estuvierais", "ellos": "estuvieran"},
        "imperfect_subjunctive_se": {"yo": "estuviese", "tu": "estuvieses", "el": "estuviese", "nosotros": "estuviésemos", "vosotros": "estuvieseis", "ellos": "estuviesen"},
        "gerund": "estando",
        "past_participle": "estado",
    },
    "ir": {
        "present_indicative": {"yo": "voy", "tu": "vas", "el": "va", "nosotros": "vamos", "vosotros": "vais", "ellos": "van"},
        "preterite": {"yo": "fui", "tu": "fuiste", "el": "fue", "nosotros": "fuimos", "vosotros": "fuisteis", "ellos": "fueron"},
        "imperfect_indicative": {"yo": "iba", "tu": "ibas", "el": "iba", "nosotros": "íbamos", "vosotros": "ibais", "ellos": "iban"},
        "present_subjunctive": {"yo": "vaya", "tu": "vayas", "el": "vaya", "nosotros": "vayamos", "vosotros": "vayáis", "ellos": "vayan"},
        "imperfect_subjunctive_ra": {"yo": "fuera", "tu": "fueras", "el": "fuera", "nosotros": "fuéramos", "vosotros": "fuerais", "ellos": "fueran"},
        "imperfect_subjunctive_se": {"yo": "fuese", "tu": "fueses", "el": "fuese", "nosotros": "fuésemos", "vosotros": "fueseis", "ellos": "fuesen"},
        "gerund": "yendo",
        "past_participle": "ido",
    },
    "haber": {
        "present_indicative": {"yo": "he", "tu": "has", "el": "ha", "nosotros": "hemos", "vosotros": "habéis", "ellos": "han"},
        "preterite": {"yo": "hube", "tu": "hubiste", "el": "hubo", "nosotros": "hubimos", "vosotros": "hubisteis", "ellos": "hubieron"},
        "future": {"yo": "habré", "tu": "habrás", "el": "habrá", "nosotros": "habremos", "vosotros": "habréis", "ellos": "habrán"},
        "conditional": {"yo": "habría", "tu": "habrías", "el": "habría", "nosotros": "habríamos", "vosotros": "habríais", "ellos": "habrían"},
        "present_subjunctive": {"yo": "haya", "tu": "hayas", "el": "haya", "nosotros": "hayamos", "vosotros": "hayáis", "ellos": "hayan"},
        "imperfect_subjunctive_ra": {"yo": "hubiera", "tu": "hubieras", "el": "hubiera", "nosotros": "hubiéramos", "vosotros": "hubierais", "ellos": "hubieran"},
        "imperfect_subjunctive_se": {"yo": "hubiese", "tu": "hubieses", "el": "hubiese", "nosotros": "hubiésemos", "vosotros": "hubieseis", "ellos": "hubiesen"},
        "gerund": "habiendo",
        "past_participle": "habido",
    },
    "dar": {
        "present_indicative": {"yo": "doy", "tu": "das", "el": "da", "nosotros": "damos", "vosotros": "dais", "ellos": "dan"},
        "preterite": {"yo": "di", "tu": "diste", "el": "dio", "nosotros": "dimos", "vosotros": "disteis", "ellos": "dieron"},
        "present_subjunctive": {"yo": "dé", "tu": "des", "el": "dé", "nosotros": "demos", "vosotros": "deis", "ellos": "den"},
        "imperfect_subjunctive_ra": {"yo": "diera", "tu": "dieras", "el": "diera", "nosotros": "diéramos", "vosotros": "dierais", "ellos": "dieran"},
        "imperfect_subjunctive_se": {"yo": "diese", "tu": "dieses", "el": "diese", "nosotros": "diésemos", "vosotros": "dieseis", "ellos": "diesen"},
        "gerund": "dando",
        "past_participle": "dado",
    },
    "ver": {
        "present_indicative": {"yo": "veo", "tu": "ves", "el": "ve", "nosotros": "vemos", "vosotros": "veis", "ellos": "ven"},
        "preterite": {"yo": "vi", "tu": "viste", "el": "vio", "nosotros": "vimos", "vosotros": "visteis", "ellos": "vieron"},
        "imperfect_indicative": {"yo": "veía", "tu": "veías", "el": "veía", "nosotros": "veíamos", "vosotros": "veíais", "ellos": "veían"},
        "present_subjunctive": {"yo": "vea", "tu": "veas", "el": "vea", "nosotros": "veamos", "vosotros": "veáis", "ellos": "vean"},
        "imperfect_subjunctive_ra": {"yo": "viera", "tu": "vieras", "el": "viera", "nosotros": "viéramos", "vosotros": "vierais", "ellos": "vieran"},
        "imperfect_subjunctive_se": {"yo": "viese", "tu": "vieses", "el": "viese", "nosotros": "viésemos", "vosotros": "vieseis", "ellos": "viesen"},
        "gerund": "viendo",
        "past_participle": "visto",
    },
    "tener": {
        "present_indicative": {"yo": "tengo", "tu": "tienes", "el": "tiene", "nosotros": "tenemos", "vosotros": "tenéis", "ellos": "tienen"},
        "preterite": {"yo": "tuve", "tu": "tuviste", "el": "tuvo", "nosotros": "tuvimos", "vosotros": "tuvisteis", "ellos": "tuvieron"},
        "future_stem": "tendr",
        "present_subjunctive": {"yo": "tenga", "tu": "tengas", "el": "tenga", "nosotros": "tengamos", "vosotros": "tengáis", "ellos": "tengan"},
        "imperfect_subjunctive_ra": {"yo": "tuviera", "tu": "tuvieras", "el": "tuviera", "nosotros": "tuviéramos", "vosotros": "tuvierais", "ellos": "tuvieran"},
        "imperfect_subjunctive_se": {"yo": "tuviese", "tu": "tuvieses", "el": "tuviese", "nosotros": "tuviésemos", "vosotros": "tuvieseis", "ellos": "tuviesen"},
        "past_participle": "tenido",
    },
    "hacer": {
        "present_indicative": {"yo": "hago", "tu": "haces", "el": "hace", "nosotros": "hacemos", "vosotros": "hacéis", "ellos": "hacen"},
        "preterite": {"yo": "hice", "tu": "hiciste", "el": "hizo", "nosotros": "hicimos", "vosotros": "hicisteis", "ellos": "hicieron"},
        "future_stem": "har",
        "present_subjunctive": {"yo": "haga", "tu": "hagas", "el": "haga", "nosotros": "hagamos", "vosotros": "hagáis", "ellos": "hagan"},
        "imperfect_subjunctive_ra": {"yo": "hiciera", "tu": "hicieras", "el": "hiciera", "nosotros": "hiciéramos", "vosotros": "hicierais", "ellos": "hicieran"},
        "imperfect_subjunctive_se": {"yo": "hiciese", "tu": "hicieses", "el": "hiciese", "nosotros": "hiciésemos", "vosotros": "hicieseis", "ellos": "hiciesen"},
        "past_participle": "hecho",
    },
    "poder": {
        "present_indicative": {"yo": "puedo", "tu": "puedes", "el": "puede", "nosotros": "podemos", "vosotros": "podéis", "ellos": "pueden"},
        "preterite": {"yo": "pude", "tu": "pudiste", "el": "pudo", "nosotros": "pudimos", "vosotros": "pudisteis", "ellos": "pudieron"},
        "future_stem": "podr",
        "present_subjunctive": {"yo": "pueda", "tu": "puedas", "el": "pueda", "nosotros": "podamos", "vosotros": "podáis", "ellos": "puedan"},
        "imperfect_subjunctive_ra": {"yo": "pudiera", "tu": "pudieras", "el": "pudiera", "nosotros": "pudiéramos", "vosotros": "pudierais", "ellos": "pudieran"},
        "imperfect_subjunctive_se": {"yo": "pudiese", "tu": "pudieses", "el": "pudiese", "nosotros": "pudiésemos", "vosotros": "pudieseis", "ellos": "pudiesen"},
        "gerund": "pudiendo",
        "past_participle": "podido",
    },
    "querer": {
        "present_indicative": {"yo": "quiero", "tu": "quieres", "el": "quiere", "nosotros": "queremos", "vosotros": "queréis", "ellos": "quieren"},
        "preterite": {"yo": "quise", "tu": "quisiste", "el": "quiso", "nosotros": "quisimos", "vosotros": "quisisteis", "ellos": "quisieron"},
        "future_stem": "querr",
        "present_subjunctive": {"yo": "quiera", "tu": "quieras", "el": "quiera", "nosotros": "queramos", "vosotros": "queráis", "ellos": "quieran"},
        "imperfect_subjunctive_ra": {"yo": "quisiera", "tu": "quisieras", "el": "quisiera", "nosotros": "quisiéramos", "vosotros": "quisierais", "ellos": "quisieran"},
        "imperfect_subjunctive_se": {"yo": "quisiese", "tu": "quisieses", "el": "quisiese", "nosotros": "quisiésemos", "vosotros": "quisieseis", "ellos": "quisiesen"},
        "past_participle": "querido",
    },
    "saber": {
        "present_indicative": {"yo": "sé", "tu": "sabes", "el": "sabe", "nosotros": "sabemos", "vosotros": "sabéis", "ellos": "saben"},
        "preterite": {"yo": "supe", "tu": "supiste", "el": "supo", "nosotros": "supimos", "vosotros": "supisteis", "ellos": "supieron"},
        "future_stem": "sabr",
        "present_subjunctive": {"yo": "sepa", "tu": "sepas", "el": "sepa", "nosotros": "sepamos", "vosotros": "sepáis", "ellos": "sepan"},
        "imperfect_subjunctive_ra": {"yo": "supiera", "tu": "supieras", "el": "supiera", "nosotros": "supiéramos", "vosotros": "supierais", "ellos": "supieran"},
        "imperfect_subjunctive_se": {"yo": "supiese", "tu": "supieses", "el": "supiese", "nosotros": "supiésemos", "vosotros": "supieseis", "ellos": "supiesen"},
        "past_participle": "sabido",
    },
    "poner": {
        "present_indicative": {"yo": "pongo", "tu": "pones", "el": "pone", "nosotros": "ponemos", "vosotros": "ponéis", "ellos": "ponen"},
        "preterite": {"yo": "puse", "tu": "pusiste", "el": "puso", "nosotros": "pusimos", "vosotros": "pusisteis", "ellos": "pusieron"},
        "future_stem": "pondr",
        "present_subjunctive": {"yo": "ponga", "tu": "pongas", "el": "ponga", "nosotros": "pongamos", "vosotros": "pongáis", "ellos": "pongan"},
        "imperfect_subjunctive_ra": {"yo": "pusiera", "tu": "pusieras", "el": "pusiera", "nosotros": "pusiéramos", "vosotros": "pusierais", "ellos": "pusieran"},
        "imperfect_subjunctive_se": {"yo": "pusiese", "tu": "pusieses", "el": "pusiese", "nosotros": "pusiésemos", "vosotros": "pusieseis", "ellos": "pusiesen"},
        "past_participle": "puesto",
    },
    "venir": {
        "present_indicative": {"yo": "vengo", "tu": "vienes", "el": "viene", "nosotros": "venimos", "vosotros": "venís", "ellos": "vienen"},
        "preterite": {"yo": "vine", "tu": "viniste", "el": "vino", "nosotros": "vinimos", "vosotros": "vinisteis", "ellos": "vinieron"},
        "future_stem": "vendr",
        "present_subjunctive": {"yo": "venga", "tu": "vengas", "el": "venga", "nosotros": "vengamos", "vosotros": "vengáis", "ellos": "vengan"},
        "imperfect_subjunctive_ra": {"yo": "viniera", "tu": "vinieras", "el": "viniera", "nosotros": "viniéramos", "vosotros": "vinierais", "ellos": "vinieran"},
        "imperfect_subjunctive_se": {"yo": "viniese", "tu": "vinieses", "el": "viniese", "nosotros": "viniésemos", "vosotros": "vinieseis", "ellos": "viniesen"},
        "gerund": "viniendo",
        "past_participle": "venido",
    },
    "decir": {
        "present_indicative": {"yo": "digo", "tu": "dices", "el": "dice", "nosotros": "decimos", "vosotros": "decís", "ellos": "dicen"},
        "preterite": {"yo": "dije", "tu": "dijiste", "el": "dijo", "nosotros": "dijimos", "vosotros": "dijisteis", "ellos": "dijeron"},
        "future_stem": "dir",
        "present_subjunctive": {"yo": "diga", "tu": "digas", "el": "diga", "nosotros": "digamos", "vosotros": "digáis", "ellos": "digan"},
        "imperfect_subjunctive_ra": {"yo": "dijera", "tu": "dijeras", "el": "dijera", "nosotros": "dijéramos", "vosotros": "dijerais", "ellos": "dijeran"},
        "imperfect_subjunctive_se": {"yo": "dijese", "tu": "dijeses", "el": "dijese", "nosotros": "dijésemos", "vosotros": "dijeseis", "ellos": "dijesen"},
        "gerund": "diciendo",
        "past_participle": "dicho",
    },
    "traer": {
        "present_indicative": {"yo": "traigo", "tu": "traes", "el": "trae", "nosotros": "traemos", "vosotros": "traéis", "ellos": "traen"},
        "preterite": {"yo": "traje", "tu": "trajiste", "el": "trajo", "nosotros": "trajimos", "vosotros": "trajisteis", "ellos": "trajeron"},
        "present_subjunctive": {"yo": "traiga", "tu": "traigas", "el": "traiga", "nosotros": "traigamos", "vosotros": "traigáis", "ellos": "traigan"},
        "imperfect_subjunctive_ra": {"yo": "trajera", "tu": "trajeras", "el": "trajera", "nosotros": "trajéramos", "vosotros": "trajerais", "ellos": "trajeran"},
        "imperfect_subjunctive_se": {"yo": "trajese", "tu": "trajeses", "el": "trajese", "nosotros": "trajésemos", "vosotros": "trajeseis", "ellos": "trajesen"},
        "gerund": "trayendo",
        "past_participle": "traído",
    },
    "caer": {
        "present_indicative": {"yo": "caigo", "tu": "caes", "el": "cae", "nosotros": "caemos", "vosotros": "caéis", "ellos": "caen"},
        "preterite": {"yo": "caí", "tu": "caíste", "el": "cayó", "nosotros": "caímos", "vosotros": "caísteis", "ellos": "cayeron"},
        "present_subjunctive": {"yo": "caiga", "tu": "caigas", "el": "caiga", "nosotros": "caigamos", "vosotros": "caigáis", "ellos": "caigan"},
        "imperfect_subjunctive_ra": {"yo": "cayera", "tu": "cayeras", "el": "cayera", "nosotros": "cayéramos", "vosotros": "cayerais", "ellos": "cayeran"},
        "imperfect_subjunctive_se": {"yo": "cayese", "tu": "cayeses", "el": "cayese", "nosotros": "cayésemos", "vosotros": "cayeseis", "ellos": "cayesen"},
        "gerund": "cayendo",
        "past_participle": "caído",
    },
    "oir": {
        "present_indicative": {"yo": "oigo", "tu": "oyes", "el": "oye", "nosotros": "oímos", "vosotros": "oís", "ellos": "oyen"},
        "preterite": {"yo": "oí", "tu": "oíste", "el": "oyó", "nosotros": "oímos", "vosotros": "oísteis", "ellos": "oyeron"},
        "present_subjunctive": {"yo": "oiga", "tu": "oigas", "el": "oiga", "nosotros": "oigamos", "vosotros": "oigáis", "ellos": "oigan"},
        "imperfect_subjunctive_ra": {"yo": "oyera", "tu": "oyeras", "el": "oyera", "nosotros": "oyéramos", "vosotros": "oyerais", "ellos": "oyeran"},
        "imperfect_subjunctive_se": {"yo": "oyese", "tu": "oyeses", "el": "oyese", "nosotros": "oyésemos", "vosotros": "oyeseis", "ellos": "oyesen"},
        "gerund": "oyendo",
        "past_participle": "oído",
    },
    "salir": {
        "present_indicative": {"yo": "salgo", "tu": "sales", "el": "sale", "nosotros": "salimos", "vosotros": "salís", "ellos": "salen"},
        "future_stem": "saldr",
        "present_subjunctive": {"yo": "salga", "tu": "salgas", "el": "salga", "nosotros": "salgamos", "vosotros": "salgáis", "ellos": "salgan"},
        "past_participle": "salido",
    },
    "valer": {
        "present_indicative": {"yo": "valgo", "tu": "vales", "el": "vale", "nosotros": "valemos", "vosotros": "valéis", "ellos": "valen"},
        "future_stem": "valdr",
        "present_subjunctive": {"yo": "valga", "tu": "valgas", "el": "valga", "nosotros": "valgamos", "vosotros": "valgáis", "ellos": "valgan"},
        "past_participle": "valido",
    },
    "caber": {
        "present_indicative": {"yo": "quepo", "tu": "cabes", "el": "cabe", "nosotros": "cabemos", "vosotros": "cabéis", "ellos": "caben"},
        "preterite": {"yo": "cupe", "tu": "cupiste", "el": "cupo", "nosotros": "cupimos", "vosotros": "cupisteis", "ellos": "cupieron"},
        "future_stem": "cabr",
        "present_subjunctive": {"yo": "quepa", "tu": "quepas", "el": "quepa", "nosotros": "quepamos", "vosotros": "quepáis", "ellos": "quepan"},
        "imperfect_subjunctive_ra": {"yo": "cupiera", "tu": "cupieras", "el": "cupiera", "nosotros": "cupiéramos", "vosotros": "cupierais", "ellos": "cupieran"},
        "imperfect_subjunctive_se": {"yo": "cupiese", "tu": "cupieses", "el": "cupiese", "nosotros": "cupiésemos", "vosotros": "cupieseis", "ellos": "cupiesen"},
        "past_participle": "cabido",
    },
    "andar": {
        "preterite": {"yo": "anduve", "tu": "anduviste", "el": "anduvo", "nosotros": "anduvimos", "vosotros": "anduvisteis", "ellos": "anduvieron"},
        "imperfect_subjunctive_ra": {"yo": "anduviera", "tu": "anduvieras", "el": "anduviera", "nosotros": "anduviéramos", "vosotros": "anduvierais", "ellos": "anduvieran"},
        "imperfect_subjunctive_se": {"yo": "anduviese", "tu": "anduvieses", "el": "anduviese", "nosotros": "anduviésemos", "vosotros": "anduvieseis", "ellos": "anduviesen"},
        "past_participle": "andado",
    },
}
